In [1]:
import numpy as np
np_a = np.array([1,2,3])
print(f'np_a的維度 {np_a.shape}')
print(np_a)
np_a2 = np_a.reshape(3,1)
print(f'np_a2的維度 {np_a2.shape}')
print(np_a2)

np_a的維度 (3,)
[1 2 3]
np_a2的維度 (3, 1)
[[1]
 [2]
 [3]]


In [2]:
np_a.reshape(-1,1).shape

(3, 1)

In [3]:
np_a.reshape(1,-1).shape

(1, 3)

In [4]:
np_a

array([1, 2, 3])

In [7]:
np.dtype(np_a[0])

dtype('int32')

In [9]:
np.NaN == np.NaN

False

In [11]:
import pandas as pd

In [27]:
scores = {'Math':[90,50,70,80],
          'English':[60,70,90,50],
          'History':[33,np.nan,np.nan,60]}

df = pd.DataFrame(scores, index=['Simon','Allen','Jimmy','Peter'])
df

Math  English  History
Simon    90       60     33.0
Allen    50       70      NaN
Jimmy    70       90      NaN
Peter    80       50     60.0

In [28]:
df.isnull()

Math  English  History
Simon  False    False    False
Allen  False    False     True
Jimmy  False    False     True
Peter  False    False    False

In [29]:
df.isnull().sum()

Math       0
English    0
History    2
dtype: int64

In [30]:
df.isnull().sum().sum()

2

In [31]:
df.isnull().any(axis=1)

Simon    False
Allen     True
Jimmy     True
Peter    False
dtype: bool

In [32]:
df[df.isnull().any(axis=1)]

Math  English  History
Allen    50       70      NaN
Jimmy    70       90      NaN

In [33]:
df['English']

Simon    60
Allen    70
Jimmy    90
Peter    50
Name: English, dtype: int64

In [34]:
df.English

Simon    60
Allen    70
Jimmy    90
Peter    50
Name: English, dtype: int64

In [35]:
df[['English']]

English
Simon       60
Allen       70
Jimmy       90
Peter       50

In [37]:
df.loc['Simon']

Math       90.0
English    60.0
History    33.0
Name: Simon, dtype: float64

In [40]:
df.iloc[2]

Math       70.0
English    90.0
History     NaN
Name: Jimmy, dtype: float64

In [49]:
df.iloc[-2:]

Math  English  History
Jimmy    70       90      NaN
Peter    80       50     60.0

In [50]:
df['Math']

Simon    90
Allen    50
Jimmy    70
Peter    80
Name: Math, dtype: int64

In [51]:
df.loc[:,'Math']

Simon    90
Allen    50
Jimmy    70
Peter    80
Name: Math, dtype: int64

In [52]:
df['個人平均'] = df.mean(axis=1)

In [53]:
df

Math  English  History       個人平均
Simon    90       60     33.0  61.000000
Allen    50       70      NaN  60.000000
Jimmy    70       90      NaN  80.000000
Peter    80       50     60.0  63.333333

In [59]:
df.loc['各科平均'] = df.mean(axis=0)

In [60]:
df

Math  English  History       個人平均  各科平均
Simon  90.0     60.0     33.0  61.000000   NaN
Allen  50.0     70.0      NaN  60.000000   NaN
Jimmy  70.0     90.0      NaN  80.000000   NaN
Peter  80.0     50.0     60.0  63.333333   NaN
各科平均   72.5     67.5     46.5  66.083333   NaN

In [62]:
s = pd.Series([1,2,3,4,5])
s.apply(lambda x: x+1 if (x%2)==1 else x-1)

0    2
1    1
2    4
3    3
4    6
dtype: int64

In [63]:
d = []
for i in s:
    if (i % 2)==1:
        d.append(i+1)
    else:
        d.append(i-1)
print(d)

[2, 1, 4, 3, 6]
